[build]
  functions = "functions"
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.8"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
