[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "build"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
