
[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
